package app.hullbeat.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

// GENERATED by tools/make_palette.py from design/palette.json - do not edit.
//
// One green ramp, because green is the BRAND and never a status. A "green =
// all good" state would be indistinguishable from ordinary chrome, and
// red/green is the hardest pair for deuteranopia. Colour is never the only
// carrier of meaning: every status pairs with text and with a glyph.

// --- brand ramp ---------------------------------------------------------
val Brand05 = Color(0xFFF2F8F6)
val Brand10 = Color(0xFFE6F0ED)
val Brand20 = Color(0xFFC2DAD4)
val Brand30 = Color(0xFF97C0B7)
val Brand40 = Color(0xFF6BA599)
val Brand50 = Color(0xFF47897C)
val Brand60 = Color(0xFF2E6C60)
val Brand70 = Color(0xFF1E5449)
val Brand80 = Color(0xFF14403A)  // seed
val Brand90 = Color(0xFF0E2E29)
val Brand95 = Color(0xFF091E1B)
val Brand99 = Color(0xFF04120F)

/**
 * Status is red / amber / neutral, never red / amber / green.
 *
 * `deferred` is here because the state exists on every card that can be put
 * off, and Compose had no slot for it: the prototype coloured it and Android
 * would have fallen back to whatever `onSurfaceVariant` happened to be.
 */
@Immutable
data class StatusColors(
    val overdue: Color,
    val dueSoon: Color,
    val ok: Color,
    val deferred: Color,
) {
    companion object {
        /** Shape fallback so status survives sunlight, greyscale and printed PDF. */
        const val GLYPH_OVERDUE = "\u25cf"  // filled circle
        const val GLYPH_DUE_SOON = "\u25d0" // half-filled circle
        const val GLYPH_OK = "\u25cb"       // hollow circle
        const val GLYPH_DEFERRED = "\u25c7" // hollow diamond
    }
}

/** The tinted plate a status line sits on, so the hue is never load-bearing alone. */
@Immutable
data class StatusTints(
    val overdue: Color,
    val dueSoon: Color,
    val deferred: Color,
)

@Immutable
data class ExtendedColors(
    val status: StatusColors,
    val tint: StatusTints,
    val divider: Color,
    /** True only for the Sunlight scheme: use 2.dp borders and skip muted greys. */
    val isHighContrast: Boolean,
    /** Sunlight promotes dividers to real borders. */
    val borderWidth: Int,
)

val LocalExtendedColors = staticCompositionLocalOf {
    ExtendedColors(
        status = StatusColors(Color.Unspecified, Color.Unspecified,
            Color.Unspecified, Color.Unspecified),
        tint = StatusTints(Color.Unspecified, Color.Unspecified, Color.Unspecified),
        divider = Color.Unspecified,
        isHighContrast = false,
        borderWidth = 1,
    )
}

// --- schemes ------------------------------------------------------------

val LightScheme: ColorScheme = lightColorScheme(
    primary = Brand80,
    onPrimary = Color.White,
    primaryContainer = Brand20,
    onPrimaryContainer = Brand90,
    secondary = Brand60,
    onSecondary = Color.White,
    secondaryContainer = Brand10,
    onSecondaryContainer = Brand90,
    background = Color(0xFFF7FAF9),
    onBackground = Color(0xFF0B1F1C),
    surface = Color.White,
    onSurface = Color(0xFF0B1F1C),
    surfaceVariant = Brand10,
    onSurfaceVariant = Color(0xFF4A5F5B),
    outline = Color(0xFF6E8781),
    outlineVariant = Color(0xFFD3E0DC),
    error = Color(0xFFB3261E),
    onError = Color.White,
)

val DarkScheme: ColorScheme = darkColorScheme(
    primary = Brand40,
    onPrimary = Brand99,
    primaryContainer = Brand70,
    onPrimaryContainer = Brand20,
    secondary = Brand30,
    onSecondary = Brand99,
    secondaryContainer = Color(0xFF172724),
    onSecondaryContainer = Brand20,
    background = Color(0xFF0A1413),
    onBackground = Color(0xFFE4EDEA),
    surface = Color(0xFF0E1A18),
    onSurface = Color(0xFFE4EDEA),
    surfaceVariant = Color(0xFF172724),
    onSurfaceVariant = Color(0xFF9BB0AB),
    outline = Color(0xFF5C716C),
    outlineVariant = Color(0xFF25332F),
    error = Color(0xFFFF8A7E),
    onError = Brand99,
)

val SunlightScheme: ColorScheme = lightColorScheme(
    primary = Brand90,
    onPrimary = Color.White,
    primaryContainer = Brand20,
    onPrimaryContainer = Brand99,
    secondary = Brand90,
    onSecondary = Color.White,
    secondaryContainer = Brand05,
    onSecondaryContainer = Brand99,
    background = Color.White,
    onBackground = Brand99,
    surface = Color.White,
    onSurface = Brand99,
    surfaceVariant = Brand05,
    onSurfaceVariant = Color(0xFF243B36),
    outline = Color(0xFF3F5651),
    outlineVariant = Color(0xFF6E8781),
    error = Color(0xFF8C1D18),
    onError = Color.White,
)

val NightScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFE8543A),
    onPrimary = Color(0xFF0A0301),
    primaryContainer = Color(0xFF2A0E07),
    onPrimaryContainer = Color(0xFFE8543A),
    secondary = Color(0xFFE8543A),
    onSecondary = Color(0xFF0A0301),
    secondaryContainer = Color(0xFF1C0A06),
    onSecondaryContainer = Color(0xFFE8543A),
    background = Color(0xFF080302),
    onBackground = Color(0xFFE8543A),
    surface = Color(0xFF0F0604),
    onSurface = Color(0xFFE8543A),
    surfaceVariant = Color(0xFF1C0A06),
    onSurfaceVariant = Color(0xFFD14A32),
    outline = Color(0xFFA34329),
    outlineVariant = Color(0xFF2A0F09),
    error = Color(0xFFFF7A55),
    onError = Color(0xFF080302),
)


val LightExtended = ExtendedColors(
    status = StatusColors(
        overdue = Color(0xFFB3261E),
        dueSoon = Color(0xFF8A5200),
        ok = Color(0xFF4A5F5B),
        deferred = Color(0xFF3D5A6C),
    ),
    tint = StatusTints(
        overdue = Color(0xFFFBE4E2),
        dueSoon = Color(0xFFFDF0DC),
        deferred = Color(0xFFE5EDF2),
    ),
    divider = Color(0xFFD3E0DC),
    isHighContrast = false,
    borderWidth = 1,
)

val DarkExtended = ExtendedColors(
    status = StatusColors(
        overdue = Color(0xFFFF8A7E),
        dueSoon = Color(0xFFFFB95C),
        ok = Color(0xFF9BB0AB),
        deferred = Color(0xFF9EC2D6),
    ),
    tint = StatusTints(
        overdue = Color(0xFF2A1614),
        dueSoon = Color(0xFF2A2010),
        deferred = Color(0xFF16242C),
    ),
    divider = Color(0xFF25332F),
    isHighContrast = false,
    borderWidth = 1,
)

val SunlightExtended = ExtendedColors(
    status = StatusColors(
        overdue = Color(0xFF8C1D18),
        dueSoon = Color(0xFF6B4000),
        ok = Color(0xFF243B36),
        deferred = Color(0xFF22404F),
    ),
    tint = StatusTints(
        overdue = Color(0xFFF7E3E1),
        dueSoon = Color(0xFFF7EEDC),
        deferred = Color(0xFFE5EDF2),
    ),
    divider = Color(0xFF6E8781),
    isHighContrast = true,
    borderWidth = 2,
)

val NightExtended = ExtendedColors(
    status = StatusColors(
        overdue = Color(0xFFFF7A55),
        dueSoon = Color(0xFFE8543A),
        ok = Color(0xFFD14A32),
        deferred = Color(0xFFD14A32),
    ),
    tint = StatusTints(
        overdue = Color(0xFF2E0E07),
        dueSoon = Color(0xFF240B05),
        deferred = Color(0xFF0F0503),
    ),
    divider = Color(0xFF2A0F09),
    isHighContrast = false,
    borderWidth = 1,
)
