plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
}

android {
    namespace = "app.hullbeat"
    compileSdk = 35

    defaultConfig {
        applicationId = "app.hullbeat"
        minSdk = 26          // SAF, notification actions and java.time all available
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
    buildFeatures { compose = true }
    packaging { resources.excludes += "/META-INF/{AL2.0,LGPL2.1}" }
}

ksp {
    // Schemas are committed so every migration can be tested against the real one.
    arg("room.schemaLocation", "$projectDir/schemas")
}

// Everything the app reads at runtime is authored in /catalog and generated by
// tools/*.py. Never edit the copies under src/main/assets - they are overwritten.
//
// This used to copy catalog.json only, while synonyms.json and checklists.json
// were written straight into assets by the Python tools. Two mechanisms for
// three files meant the comment above was true of one of them, and the assets
// copy of the other two had no source of truth to be regenerated from - the
// same drift class that put "джекштоки" in the checklists.
val copyCatalog = tasks.register<Copy>("copyCatalog") {
    from(rootProject.file("catalog")) {
        // schema.json validates the catalog at author time; it does not ship.
        include("catalog.json", "synonyms.json", "checklists.json")
    }
    into(layout.projectDirectory.dir("src/main/assets/catalog"))
}
tasks.named("preBuild") { dependsOn(copyCatalog) }

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui.tooling.preview)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.androidx.documentfile)
    implementation(libs.kotlinx.serialization.json)

    implementation(libs.mlkit.text.recognition)
    implementation(libs.mlkit.barcode.scanning)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.room.testing)
}
