#!/usr/bin/env python3
"""Every type a Kotlin file names must be imported or live in its own package.

WHY THIS EXISTS

Roughly a thousand lines of Kotlin have been written in this project without a
compiler ever seeing them: there is no Android SDK here, no Gradle, and the
local JDK is 25 while AGP 8.9 wants 17-21. The symbol audits done by hand
catch a name that does not exist anywhere. They cannot catch a name that
exists and is not imported - which is the single likeliest way freshly written
Kotlin fails its first build.

This is NOT a compiler and does not pretend to be. It answers one question:
is every capitalised identifier used as a type or an object reference either
imported, declared in the same package, or a well-known stdlib name?

FALSE POSITIVES ARE THE FAILURE MODE. A check that cries wolf gets ignored -
this project already threw away a first plural heuristic that produced five
false positives out of seven findings. So the matcher is deliberately narrow:
only identifiers that start a reference chain, never ALL_CAPS constants, never
single-letter type parameters, and never anything declared anywhere in the
same package.

Run:  python tools/check_kotlin_imports.py
Exit: 1 if a type is used with no visible import.
"""
import io
import os
import re
import sys

ROOTS = [
    os.path.join("app", "src", "main", "java"),
    os.path.join("app", "src", "test", "java"),
]

# Names available without an import in every Kotlin file. Not exhaustive by
# design: anything missing here shows up as a finding once, gets checked, and
# gets added if it is genuinely implicit.
STDLIB = {
    "Any", "Array", "Boolean", "Byte", "Char", "CharSequence", "Comparable",
    "Double", "Enum", "Exception", "Float", "IllegalArgumentException",
    "IllegalStateException", "Int", "Iterable", "Iterator", "List", "Long",
    "Map", "MutableList", "MutableMap", "MutableSet", "Nothing", "Number",
    "Pair", "Result", "RuntimeException", "Sequence", "Set", "Short",
    "String", "StringBuilder", "Throwable", "Triple", "UInt", "ULong", "Unit",
    "Regex", "Lazy", "Deprecated", "JvmStatic", "JvmField", "JvmOverloads",
    # java.lang is implicit on Kotlin/JVM, exactly as in Java.
    "System", "Math", "Runtime", "Thread", "Object", "Class",
    "Suppress", "OptIn", "Volatile", "Synchronized", "Transient",
}

# Types, and also top-level vals and funs: a package exports all of them to
# itself. `val Brand80`, `fun HullBeatTheme` and `private fun Placeholder` are
# every bit as visible as a class, and treating only classes as declarations
# produced thirty false findings on the first run.
MODIFIERS = (r"(?:public |internal |private |protected |abstract |open |sealed "
             r"|data |enum |value |annotation |inner |const |lateinit "
             r"|expect |actual |external |infix |inline |operator |suspend "
             r"|tailrec )*")
_DECL_TAIL = (r"(?:@\w+(?:\([^)]*\))?\s+)*" + MODIFIERS +
              r"(?:class|interface|object|typealias|val|var|fun)\s+(?:<[^>]+>\s*)?([A-Z]\w*)")
# Top level: visible to the whole package.
TOP_DECL_RE = re.compile(r"^" + _DECL_TAIL, re.M)
# Any depth: visible at least inside its own file, which is all this check
# needs to stop flagging `Input` inside `object DueCalculator`.
ANY_DECL_RE = re.compile(r"^\s*" + _DECL_TAIL, re.M)
# Everything a package exports by name, for resolving imports: types, and
# top-level funs and vals whatever their case, extension receiver skipped.
EXPORT_RE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s+)*" + MODIFIERS +
    r"(?:class|interface|object|typealias|annotation class)\s+(\w+)"
    r"|^(?:@\w+(?:\([^)]*\))?\s+)*" + MODIFIERS +
    r"(?:fun|val|var)\s+(?:<[^>]+>\s*)?(?:[\w.<>, ?]+\.)?(\w+)",
    re.M)
IMPORT_RE = re.compile(r"^import\s+([\w.]+)(?:\s+as\s+(\w+))?", re.M)
PACKAGE_RE = re.compile(r"^package\s+([\w.]+)", re.M)
# A capitalised name that STARTS a reference: not preceded by a dot or a word
# character, so `db.Foo` and `MyFoo` never match on `Foo`.
USE_RE = re.compile(r"(?<![\w.])([A-Z][A-Za-z0-9]*)\b")


def strip_noise(src):
    """Remove comments and string literals so their words are not read as code."""
    src = re.sub(r'"""(?:.|\n)*?"""', '""', src)
    src = re.sub(r'(?<!\\)"(?:[^"\\\n]|\\.)*"', '""', src)
    src = re.sub(r"/\*(?:.|\n)*?\*/", "", src)
    src = re.sub(r"//[^\n]*", "", src)
    # Backtick identifiers. Kotlin test names are whole English sentences,
    # and `ashore in January, the prediction lands after launch` reads as a
    # reference to a type called January unless they are stripped.
    src = re.sub(r"`[^`\n]*`", "x", src)
    return src


# Imports below this root are ours, so they can be resolved against what the
# project actually declares. Everything else is a library we cannot see.
OWN_ROOT = "app.hullbeat."

# Generated by AGP at build time, never present in sources.
GENERATED = {"app.hullbeat.R", "app.hullbeat.BuildConfig"}


def main():
    files = []
    for root in ROOTS:
        for dirpath, _, names in os.walk(root):
            files += [os.path.join(dirpath, n) for n in names if n.endswith(".kt")]
    if not files:
        print("no Kotlin sources found")
        return 1

    # What each package declares, so same-package references need no import.
    by_package = {}
    exports = {}          # everything a package exports, for import checking
    in_file = {}
    raw = {}
    for path in files:
        src = io.open(path, encoding="utf-8").read()
        raw[path] = src
        pkg = PACKAGE_RE.search(src)
        pkg = pkg.group(1) if pkg else ""
        by_package.setdefault(pkg, set()).update(TOP_DECL_RE.findall(src))
        exports.setdefault(pkg, set()).update(
            n for pair in EXPORT_RE.findall(src) for n in pair if n)
        in_file[path] = set(ANY_DECL_RE.findall(src))

    problems = []
    checked = 0
    for path in sorted(files):
        src = raw[path]
        pkg = PACKAGE_RE.search(src)
        pkg = pkg.group(1) if pkg else ""

        visible = (set(STDLIB) | by_package.get(pkg, set())
                   | in_file.get(path, set()))
        for full, alias in IMPORT_RE.findall(src):
            visible.add(alias or full.rsplit(".", 1)[-1])
            if (full.startswith(OWN_ROOT) and not full.endswith(".*")
                    and full not in GENERATED
                    and not full.startswith("app.hullbeat.R.")):
                owner, _, name = full.rpartition(".")
                declared = exports.get(owner)
                if declared is not None and name not in declared:
                    # `import a.b.Type.Member` - an enum entry, a companion,
                    # a nested class. Resolvable only as far as the type.
                    parent_owner, _, parent = owner.rpartition(".")
                    nested = exports.get(parent_owner)
                    if nested is not None and parent in nested:
                        continue
                    near = sorted(n for n in declared
                                  if n.lower().startswith(name.lower()[:5]))
                    problems.append(
                        "%s: imports %s, but %s declares no such name%s"
                        % (path, full, owner,
                           " (did you mean %s?)" % ", ".join(near[:3])
                           if near else ""))
            # A star import makes everything in that package visible; the
            # project does not use them, but assuming they do not exist would
            # produce a wall of false findings the day someone adds one.
            if full.endswith(".*"):
                visible |= by_package.get(full[:-2], set())
                visible.add("*")
        if "*" in visible:
            continue

        body = strip_noise(src)
        for name in sorted(set(USE_RE.findall(body))):
            checked += 1
            if name in visible or name.isupper() or len(name) == 1:
                continue
            problems.append("%s: %s is used but never imported" % (path, name))

    for p in problems:
        print("  ERROR " + p)
    print("%d Kotlin files, %d type references checked" % (len(files), checked))
    if problems:
        print("FAILED: %d unimported name(s)" % len(problems))
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
