#!/usr/bin/env python3
"""Generate localised string resources from the catalog and the term glossaries.

The catalog holds codes plus an English fallback; every translation lives in
catalog/i18n/<locale>.json. This turns both into values*/strings_catalog.xml and
reports what is missing, extra or still awaiting a sailor's review.

Run:  python tools/make_strings.py
Exit: 1 if any locale is missing a key the catalog defines.
"""
import io
import json
import os
import re
import sys
from xml.sax.saxutils import escape

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import profile_labels

CATALOG = os.path.join("catalog", "catalog.json")
I18N_DIR = os.path.join("catalog", "i18n")
CHECKLISTS = os.path.join("catalog", "checklists.json")
RES = os.path.join("app", "src", "main", "res")

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
    GENERATED by tools/make_strings.py - do not edit.
    Source: catalog/catalog.json{source}
    Category keys are cat_<code>, component keys are cmp_<code>.
-->
<resources>
"""


def esc(text):
    """XML-escape, then guard the two characters Android treats specially."""
    return escape(text).replace("'", "\\'").replace('"', '\\"')


def load_catalog():
    with io.open(CATALOG, encoding="utf-8") as fh:
        return json.load(fh)


def catalog_keys(catalog):
    cats, comps = [], []
    for category in catalog["categories"]:
        cats.append((category["code"], category["en"]))
        for component in category["components"]:
            comps.append((component["code"], component["en"]))
    return cats, comps


def write_xml(path, rows, source):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = [HEADER.format(source=source)]
    section = None
    for kind, key, value in rows:
        if kind != section:
            body.append(f"\n    <!-- {kind} -->\n")
            section = kind
        body.append(f'    <string name="{key}">{esc(value)}</string>\n')
    body.append("</resources>\n")
    io.open(path, "w", encoding="utf-8", newline="\n").write("".join(body))


def profile_keys():
    """(resource name, English, Ukrainian) for the nine profile axes.

    Nothing asked an owner what boat they own until the first build was put
    on a phone and showed an empty screen, so these words never existed.
    They are checked BOTH ways against catalog.json: a vocabulary value with
    no label, or a label for a value the catalog dropped, fails here rather
    than showing a raw code like `saildrive` to a person.
    """
    vocab = json.load(io.open(CATALOG, encoding="utf-8"))["profileVocabulary"]
    pairs = {(axis, value) for axis, values in vocab.items() for value in values}
    missing = sorted(pairs - set(profile_labels.VALUES))
    extra = sorted(set(profile_labels.VALUES) - pairs)
    if missing or extra:
        raise SystemExit(
            "tools/profile_labels.py is out of step with catalog.json:%s%s"
            % ("".join("\n    no label for %s.%s" % kv for kv in missing),
               "".join("\n    label for %s.%s, which the catalog does not have"
                       % kv for kv in extra)))
    rows = [("axis_%s" % axis, en, uk)
            for axis, (en, uk) in sorted(profile_labels.AXES.items())]
    rows += [("opt_%s_%s" % (axis, value), en, uk)
             for (axis, value), (en, uk) in sorted(profile_labels.VALUES.items())]
    return rows


def hint_slug(label):
    """A resource name for an English label like "Alarm threshold (°C)".

    `%` and `°` carry meaning and have to survive: without them "Size" and
    "Size %" collapse onto the same key and one silently wins.
    """
    out = label.lower().replace("%", " pct ").replace("\u00b0", " deg ")
    return re.sub(r"[^a-z0-9]+", "_", out).strip("_")


def spechint_keys(glossary=None):
    """(slug, english, ukrainian-or-None) for every passport label in use."""
    hints = json.load(io.open(CATALOG, encoding="utf-8"))
    used = []
    seen = set()
    for cat in hints["categories"]:
        for comp in cat["components"]:
            for label in comp.get("specHints") or []:
                if label not in seen:
                    seen.add(label)
                    used.append(label)
    slugs = {}
    for label in used:
        slug = hint_slug(label)
        if slug in slugs:
            raise SystemExit(
                "spec-hint slug collision: %r and %r both give %r"
                % (slugs[slug], label, slug))
        slugs[slug] = label
    uk = (glossary or {}).get("specHints") or {}
    return [(hint_slug(label), label,
             (lambda v: v[0] if isinstance(v, list) else v)(uk[label])
             if label in uk else None)
            for label in sorted(used)]


def checklist_keys():
    """(code, english) for every checklist and every item in it.

    Checklist text was reaching the screen from a `"uk"` field inside
    catalog/checklists.json, chosen by a locale branch in Kotlin. That is a
    SECOND localisation mechanism running beside Android's: a third language
    could never be added, a translator could never touch it, and
    check_translations.py could not see it, because a string that never became
    a resource does not exist as far as that check is concerned.

    The Ukrainian was already in catalog/i18n/uk.json under chk_<code>. Only
    the generator was not emitting it.
    """
    data = json.load(io.open(CHECKLISTS, encoding="utf-8"))
    out = []
    for cl in data["checklists"]:
        out.append((cl["code"], cl["en"]))
        for item in cl["items"]:
            out.append((item["code"], item["en"]))
    return out


def main():
    catalog = load_catalog()
    cats, comps = catalog_keys(catalog)
    checks = checklist_keys()
    hints = spechint_keys()
    profile = profile_keys()
    expected = ({f"cat_{c}" for c, _ in cats} | {f"cmp_{c}" for c, _ in comps}
                | {f"chk_{c}" for c, _ in checks}
                | {f"hint_{slug}" for slug, _, _ in hints}
                | {key for key, _, _ in profile})

    # English comes straight from the catalog: one source of truth, no drift.
    rows = [("categories", f"cat_{code}", en) for code, en in cats]
    rows += [("components", f"cmp_{code}", en) for code, en in comps]
    rows += [("checklists", f"chk_{code}", en) for code, en in checks]
    rows += [("passport labels", f"hint_{slug}", en) for slug, en, _ in hints]
    rows += [("vessel profile", key, en) for key, en, _ in profile]
    write_xml(os.path.join(RES, "values", "strings_catalog.xml"), rows, "")
    print(f"values/strings_catalog.xml            {len(rows):3} keys  (English, from catalog)")

    failed = False
    synonyms = {}
    for name in sorted(os.listdir(I18N_DIR)):
        if not name.endswith(".json"):
            continue
        locale = os.path.splitext(name)[0]
        with io.open(os.path.join(I18N_DIR, name), encoding="utf-8") as fh:
            glossary = json.load(fh)

        # A locale file may be aliases only (English display names come from
        # the catalog), so an empty components block is normal, not an error.
        aliases_only = not glossary.get("components")

        terms = {}
        confidence = {}
        for code, (term, conf) in glossary.get("categories", {}).items():
            terms[f"cat_{code}"] = term
            confidence[f"cat_{code}"] = conf
        for code, (term, conf) in glossary.get("components", {}).items():
            terms[f"cmp_{code}"] = term
            confidence[f"cmp_{code}"] = conf
        # uk.json has carried the 117 chk_* translations all along; only the
        # generator was not reading them, which is why the app ended up with a
        # second localisation mechanism inside a JSON asset.
        for key, (term, conf) in glossary.get("checklists", {}).items():
            terms[key] = term
            confidence[key] = conf
        for key, _, uk in profile:
            terms[key] = uk
            confidence[key] = "check"
        for slug, _, uk in spechint_keys(glossary):
            if uk:
                terms[f"hint_{slug}"] = uk
                confidence[f"hint_{slug}"] = (
                    glossary["specHints"][_][1]
                    if isinstance(glossary["specHints"].get(_), list) else "check")

        # Aliases are keyed by the bare component code, not the cmp_ resource key.
        synonyms[locale] = glossary.get("synonyms", {})
        bad_codes = sorted(set(synonyms[locale]) - {c for c, _ in comps})
        if bad_codes:
            failed = True
            print(f"    ALIAS for unknown code: {', '.join(bad_codes[:8])}")

        if aliases_only:
            n = sum(len(v) for v in synonyms[locale].values())
            print(f"catalog/i18n/{name:<22} aliases only: "
                  f"{len(synonyms[locale])} components, {n} phrases")
            continue

        missing = sorted(expected - set(terms))
        extra = sorted(set(terms) - expected)

        rows = [("categories", f"cat_{code}", terms[f"cat_{code}"])
                for code, _ in cats if f"cat_{code}" in terms]
        rows += [("components", f"cmp_{code}", terms[f"cmp_{code}"])
                 for code, _ in comps if f"cmp_{code}" in terms]
        rows += [("checklists", f"chk_{code}", terms[f"chk_{code}"])
                 for code, _ in checks if f"chk_{code}" in terms]
        rows += [("passport labels", f"hint_{slug}", uk)
                 for slug, _, uk in spechint_keys(glossary) if uk]
        rows += [("vessel profile", key, uk) for key, _, uk in profile]
        write_xml(os.path.join(RES, f"values-{locale}", "strings_catalog.xml"),
                  rows, f" + catalog/i18n/{name}")

        counts = {"ok": 0, "check": 0, "descr": 0}
        for key in terms:
            counts[confidence.get(key, "check")] = counts.get(confidence.get(key, "check"), 0) + 1

        print(f"values-{locale}/strings_catalog.xml         {len(rows):3} keys  "
              f"settled {counts['ok']}, needs review {counts['check']}, coined {counts['descr']}")

        if missing:
            failed = True
            print(f"    MISSING {len(missing)}: {', '.join(missing[:8])}"
                  f"{' ...' if len(missing) > 8 else ''}")
        if extra:
            print(f"    EXTRA {len(extra)} (not in catalog): {', '.join(extra[:8])}")

        # Checklist lines are sentences, not terms, and catalog/i18n/
        # uk-checklists-review.md already presents them with the English, the
        # catalog node and the journal effect. Listing them here as well gave
        # 117 rows with an empty English column and hid the real terms.
        review = sorted(k for k, c in confidence.items()
                        if c == "check" and not k.startswith("chk_"))
        out = os.path.join("catalog", "i18n", f"{locale}-review.md")
        n_terms = sum(1 for k in terms if not k.startswith("chk_"))
        n_chk = len(terms) - n_terms
        if review:
            lines = [f"# Терміни на перевірку — {locale}\n",
                     f"\n{len(review)} з {n_terms} потребують підтвердження від людини, ",
                     "яка ходить під вітрилом. Решта — усталені або описові.\n",
                     "\nПитання до кожного одне: **чи так це називають на воді?**\n",
                     f"\nРядки чеклістів ({n_chk} шт.) — окремо, у "
                     "`uk-checklists-review.md`: там видно й вузол, і чи "
                     "створює пункт запис у журналі.\n",
                     "\n| Ключ | Англійською | Наш варіант | Правка |\n|---|---|---|---|\n"]
            en_by_key = {f"cat_{c}": e for c, e in cats}
            en_by_key.update({f"cmp_{c}": e for c, e in comps})
            for key in review:
                lines.append(f"| `{key}` | {en_by_key.get(key, '')} | **{terms[key]}** | |\n")
            io.open(out, "w", encoding="utf-8", newline="\n").writelines(lines)
            print(f"    review list -> {out}  ({len(review)} terms)")
        else:
            lines = [f"# Терміни на перевірку — {locale}\n",
                     f"\n0 з {n_terms} потребують підтвердження. Усі терміни затверджено.\n",
                     f"\nРядки чеклістів ({n_chk} шт.) — окремо, у "
                     "`uk-checklists-review.md`: там видно й вузол, і чи "
                     "створює пункт запис у журналі.\n"]
            io.open(out, "w", encoding="utf-8", newline="\n").writelines(lines)
            print(f"    review list -> {out}  (0 terms, all verified)")

    # Aliases are not Android strings - they are never displayed. They ship as
    # an asset and go into the FTS body at seed time, so a search matches them
    # while the UI keeps showing one canonical name.
    total = sum(len(v) for loc in synonyms.values() for v in loc.values())
    # Source of truth lives in /catalog; app/build.gradle.kts copies it into
    # assets at build time, like catalog.json and checklists.json.
    out = os.path.join("catalog", "synonyms.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with io.open(out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(synonyms, fh, ensure_ascii=False, indent=2, sort_keys=True)
        fh.write("\n")
    covered = {c for loc in synonyms.values() for c in loc}
    n_comps = len(comps)
    print(f"\ncatalog/synonyms.json                 {total} phrases over "
          f"{len(covered)} of {n_comps} components "
          f"({100 * len(covered) // n_comps}%)")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
