#!/usr/bin/env python3
"""Generate every consumer of the palette from design/palette.json.

WHY THIS EXISTS

The palette lived in six places, two pairs of which were byte-identical
duplicates kept in step by hand:

  1. design/Color.kt                              | literally the same file
  2. app/src/main/java/app/hullbeat/ui/theme/Color.kt
  3. design/colors.xml                             | literally the same file
  4. app/src/main/res/values/colors.xml
  5. tools/check_contrast.py - its own `P` dict, under the comment
     "keep in sync with design/Color.kt"
  6. prototype/index.html - CSS custom properties, and the only place with
     all four schemes

`make_logo.py` held a seventh copy of the seed tone as `BRAND = "#14403A"`.

The consequences were already visible: the night scheme existed only in the
prototype, so Compose had three schemes where the design has four, the
deferred state and the three tint colours had no Compose slot at all, and
nothing had ever contrast-checked night.

Run:  python tools/make_palette.py
Exit: 1 if a generated file cannot be written or the JSON is inconsistent.
"""
import io
import json
import os
import sys
from collections import OrderedDict

SOURCE = os.path.join("design", "palette.json")
KT = os.path.join("app", "src", "main", "java", "app", "hullbeat", "ui",
                  "theme", "Color.kt")
XML = os.path.join("app", "src", "main", "res", "values", "colors.xml")
XML_NIGHT = os.path.join("app", "src", "main", "res", "values-night",
                         "colors.xml")
PROTO = os.path.join("prototype", "index.html")

# Material3 roles a ColorScheme needs, and which semantic token fills each when
# a scheme has no hand-tuned mapping of its own. Night is the case: it was
# designed as CSS and its roles are DERIVED here rather than guessed, so the
# derivation is one reviewable table instead of eighteen typed hexes.
#
# `secondary` collapses onto `primary` on purpose for such a scheme: the whole
# constraint of a red-on-black night palette is that there is no second hue
# left to spend - see ui-spec.md §8.2.
DERIVE = OrderedDict([
    ("primary", "primary"),
    ("onPrimary", "onPrimary"),
    ("primaryContainer", "primaryContainer"),
    ("onPrimaryContainer", "onPrimaryContainer"),
    ("secondary", "primary"),
    ("onSecondary", "onPrimary"),
    ("secondaryContainer", "surfaceVariant"),
    ("onSecondaryContainer", "onSurface"),
    ("background", "background"),
    ("onBackground", "onSurface"),
    ("surface", "surface"),
    ("onSurface", "onSurface"),
    ("surfaceVariant", "surfaceVariant"),
    ("onSurfaceVariant", "onSurfaceMuted"),
    ("outline", "outline"),
    ("outlineVariant", "divider"),
    ("error", "statusOverdue"),
    ("onError", "background"),
])

RAMP_BY_HEX = {}


def kt_expr(hexval):
    """Prefer the ramp constant, so Color.kt still reads as a system."""
    if hexval == "#FFFFFF":
        return "Color.White"
    if hexval == "#000000":
        return "Color.Black"
    if hexval in RAMP_BY_HEX:
        return RAMP_BY_HEX[hexval]
    return "Color(0xFF%s)" % hexval.lstrip("#").upper()


def argb(hexval):
    return "#FF" + hexval.lstrip("#").upper()


def snake(name):
    out = []
    for ch in name:
        if ch.isupper():
            out.append("_")
            out.append(ch.lower())
        else:
            out.append(ch)
    return "".join(out)


def load():
    p = json.load(io.open(SOURCE, encoding="utf-8"),
                  object_pairs_hook=OrderedDict)
    for step, hexval in p["brand"].items():
        RAMP_BY_HEX[hexval] = "Brand" + step
    changed = False
    for name, s in p["schemes"].items():
        if s.get("material"):
            continue
        # Fill it in and write it back, so the mapping is visible in the
        # source rather than hidden in this script.
        s["material"] = OrderedDict(
            (role, s["tokens"][token]) for role, token in DERIVE.items())
        s["_materialDerived"] = (
            "Roles derived from this scheme's own tokens by "
            "tools/make_palette.py DERIVE; edit freely, the generator will "
            "not overwrite a mapping that is present.")
        changed = True
        print("  derived Material3 roles for scheme '%s'" % name)
    if changed:
        io.open(SOURCE, "w", encoding="utf-8", newline="\n").write(
            json.dumps(p, ensure_ascii=False, indent=2) + "\n")
    return p


# ---------------------------------------------------------------- Color.kt
KT_HEAD = '''package app.hullbeat.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

// GENERATED by tools/make_palette.py from design/palette.json - do not edit.
//
// One green ramp, because green is the BRAND and never a status. A "green =
// all good" state would be indistinguishable from ordinary chrome, and
// red/green is the hardest pair for deuteranopia. Colour is never the only
// carrier of meaning: every status pairs with text and with a glyph.

'''

KT_TYPES = '''
/**
 * Status is red / amber / neutral, never red / amber / green.
 *
 * `deferred` is here because the state exists on every card that can be put
 * off, and Compose had no slot for it: the prototype coloured it and Android
 * would have fallen back to whatever `onSurfaceVariant` happened to be.
 */
@Immutable
data class StatusColors(
    val overdue: Color,
    val dueSoon: Color,
    val ok: Color,
    val deferred: Color,
) {
    companion object {
        /** Shape fallback so status survives sunlight, greyscale and printed PDF. */
        const val GLYPH_OVERDUE = "\\u25cf"  // filled circle
        const val GLYPH_DUE_SOON = "\\u25d0" // half-filled circle
        const val GLYPH_OK = "\\u25cb"       // hollow circle
        const val GLYPH_DEFERRED = "\\u25c7" // hollow diamond
    }
}

/** The tinted plate a status line sits on, so the hue is never load-bearing alone. */
@Immutable
data class StatusTints(
    val overdue: Color,
    val dueSoon: Color,
    val deferred: Color,
)

@Immutable
data class ExtendedColors(
    val status: StatusColors,
    val tint: StatusTints,
    val divider: Color,
    /** True only for the Sunlight scheme: use 2.dp borders and skip muted greys. */
    val isHighContrast: Boolean,
    /** Sunlight promotes dividers to real borders. */
    val borderWidth: Int,
)

val LocalExtendedColors = staticCompositionLocalOf {
    ExtendedColors(
        status = StatusColors(Color.Unspecified, Color.Unspecified,
            Color.Unspecified, Color.Unspecified),
        tint = StatusTints(Color.Unspecified, Color.Unspecified, Color.Unspecified),
        divider = Color.Unspecified,
        isHighContrast = false,
        borderWidth = 1,
    )
}
'''


def gen_kt(p):
    out = [KT_HEAD, "// --- brand ramp ---------------------------------------------------------\n"]
    for step, hexval in p["brand"].items():
        seed = "  // seed" if p["seed"] == "brand." + step else ""
        out.append("val Brand%s = Color(0xFF%s)%s\n"
                   % (step, hexval.lstrip("#").upper(), seed))
    out.append(KT_TYPES)
    out.append("\n// --- schemes ------------------------------------------------------------\n")
    for name, s in p["schemes"].items():
        cap = name[0].upper() + name[1:]
        builder = "lightColorScheme" if name in ("light", "sunlight") else "darkColorScheme"
        out.append("\nval %sScheme: ColorScheme = %s(\n" % (cap, builder))
        for role, hexval in s["material"].items():
            out.append("    %s = %s,\n" % (role, kt_expr(hexval)))
        out.append(")\n")
    out.append("\n")
    for name, s in p["schemes"].items():
        cap = name[0].upper() + name[1:]
        t = s["tokens"]
        out.append("\nval %sExtended = ExtendedColors(\n" % cap)
        out.append("    status = StatusColors(\n")
        for field, token in (("overdue", "statusOverdue"), ("dueSoon", "statusDueSoon"),
                             ("ok", "statusOk"), ("deferred", "statusDeferred")):
            out.append("        %s = %s,\n" % (field, kt_expr(t[token])))
        out.append("    ),\n")
        out.append("    tint = StatusTints(\n")
        for field, token in (("overdue", "tintOverdue"), ("dueSoon", "tintDueSoon"),
                             ("deferred", "tintDeferred")):
            out.append("        %s = %s,\n" % (field, kt_expr(t[token])))
        out.append("    ),\n")
        out.append("    divider = %s,\n" % kt_expr(t["divider"]))
        out.append("    isHighContrast = %s,\n"
                   % ("true" if s["isHighContrast"] else "false"))
        out.append("    borderWidth = %s,\n" % s["borderWidth"].rstrip("px"))
        out.append(")\n")
    return "".join(out)


# --------------------------------------------------------------- colors.xml
def gen_xml(p, scheme="light", night=False):
    light = p["schemes"][scheme]["tokens"]
    out = ['<?xml version="1.0" encoding="utf-8"?>\n',
           "<!--\n",
           "  GENERATED by tools/make_palette.py from design/palette.json - do not edit.\n",
           "\n",
           "  XML fallback for surfaces Compose does not reach: notification accent,\n",
           "  home-screen widgets, launcher background, splash theme.\n",
           "\n",
           ("  Dark overrides, applied by the system in night mode.\n"
            if night else
            "  Light values. values-night/colors.xml carries the dark overrides.\n"),
           "-->\n",
           "<resources>\n\n",
           ]
    if not night:
        out.append("    <!-- brand ramp -->\n")
        for step, hexval in p["brand"].items():
            out.append('    <color name="brand_%s">%s</color>\n'
                       % (step, argb(hexval)))
    if not night:
        out.append("\n")
    out.append("    <!-- semantic: %s -->\n" % scheme)
    for token in ("background", "surface", "surfaceVariant", "onSurface",
                  "onSurfaceMuted", "primary", "onPrimary", "primaryContainer",
                  "onPrimaryContainer", "outline", "divider"):
        out.append('    <color name="%s">%s</color>\n'
                   % (snake(token), argb(light[token])))
    out.append("\n    <!-- maintenance status: red / amber / neutral.\n")
    out.append("         Green is reserved for the brand - see design/README.md -->\n")
    for token in ("statusOverdue", "statusDueSoon", "statusOk", "statusDeferred"):
        out.append('    <color name="%s">%s</color>\n'
                   % (snake(token), argb(light[token])))
    out.append("\n    <!-- notification accent: must stay legible on both the system light\n")
    out.append("         and dark shade, so it uses the mid ramp rather than the seed tone -->\n")
    out.append('    <color name="notification_accent">%s</color>\n'
               % argb(p["brand"]["60"]))
    out.append("\n</resources>\n")
    return "".join(out)


# ------------------------------------------------------- prototype css block
CSS_TOKEN = OrderedDict([
    ("bg", "background"), ("surface", "surface"), ("variant", "surfaceVariant"),
    ("ink", "onSurface"), ("muted", "onSurfaceMuted"),
    ("primary", "primary"), ("on-primary", "onPrimary"),
    ("container", "primaryContainer"), ("on-container", "onPrimaryContainer"),
    ("outline", "outline"), ("divider", "divider"),
    ("overdue", "statusOverdue"), ("soon", "statusDueSoon"),
    ("ok", "statusOk"), ("deferred", "statusDeferred"),
    ("tint-overdue", "tintOverdue"), ("tint-soon", "tintDueSoon"),
    ("tint-deferred", "tintDeferred"),
])
LINES = [("bg", "surface", "variant"), ("ink", "muted"),
         ("primary", "on-primary"), ("container", "on-container"),
         ("outline", "divider"),
         ("overdue", "soon", "ok", "deferred"),
         ("tint-overdue", "tint-soon", "tint-deferred")]


def gen_css(p):
    out = []
    for name, s in p["schemes"].items():
        t = s["tokens"]
        out.append('.device[data-scheme="%s"] {\n' % s["cssName"])
        for group in LINES:
            out.append("  " + " ".join(
                "--%s: %s;" % (css, t[CSS_TOKEN[css]]) for css in group) + "\n")
        out.append("  --border-w: %s;\n}\n" % s["borderWidth"])
    return "".join(out)


def main():
    p = load()

    io.open(KT, "w", encoding="utf-8", newline="\n").write(gen_kt(p))
    print("%-58s %d schemes" % (KT, len(p["schemes"])))

    io.open(XML, "w", encoding="utf-8", newline="\n").write(gen_xml(p))
    print("%-58s light" % XML)

    os.makedirs(os.path.dirname(XML_NIGHT), exist_ok=True)
    io.open(XML_NIGHT, "w", encoding="utf-8", newline="\n").write(
        gen_xml(p, scheme="dark", night=True))
    print("%-58s dark overrides" % XML_NIGHT)

    html = io.open(PROTO, encoding="utf-8").read()
    start = html.index('.device[data-scheme="light"] {')
    end = html.index("/* ---------- device", start)
    new = html[:start] + gen_css(p) + "\n" + html[end:]
    io.open(PROTO, "w", encoding="utf-8", newline="\n").write(new)
    print("%-58s %d schemes" % (PROTO, len(p["schemes"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
