#!/usr/bin/env python3
"""Generate SearchConfig.kt and verify search constants across consumers from design/search-ranking.json.

WHY THIS EXISTS
Scoring weights, stemming floor and penalties were duplicated between the
prototype JS, Kotlin domain logic and check_search.py. Keeping them aligned
by comments is how drift happens. design/search-ranking.json is the single source
of truth.

Run: python tools/make_search_config.py
Exit: 1 if design/search-ranking.json cannot be read or output cannot be written.
"""
import io
import json
import os
import re
import sys

CONFIG = os.path.join("design", "search-ranking.json")
KT_OUT = os.path.join("app", "src", "main", "java", "app", "hullbeat", "domain", "search", "SearchConfig.kt")
PROTO = os.path.join("prototype", "index.html")

def main():
    if not os.path.exists(CONFIG):
        print(f"Missing {CONFIG}")
        return 1

    with io.open(CONFIG, encoding="utf-8") as fh:
        data = json.load(fh)

    stem_cost = data["stemCost"]
    min_stem = data["minStemLength"]
    max_dropped = data["maxDroppedChars"]
    scores = data["scores"]

    # 1. Generate Kotlin SearchConfig.kt
    os.makedirs(os.path.dirname(KT_OUT), exist_ok=True)
    kt_code = """package app.hullbeat.domain.search

/**
 * GENERATED by tools/make_search_config.py from design/search-ranking.json - do not edit.
 *
 * Scoring and morphological rules for HullBeat search (docs/search-spec.md).
 */
object SearchConfig {
    const val STEM_COST = """ + str(stem_cost) + """
    const val MIN_STEM_LENGTH = """ + str(min_stem) + """
    const val MAX_DROPPED_CHARS = """ + str(max_dropped) + """

    object Scores {
        const val EXACT_TITLE = """ + str(scores["exactTitle"]) + """
        const val EXACT_EN_TITLE = """ + str(scores["exactEnTitle"]) + """
        const val PREFIX_TITLE = """ + str(scores["prefixTitle"]) + """
        const val PREFIX_EN_TITLE = """ + str(scores["prefixEnTitle"]) + """
        const val WORD_PREFIX_TITLE = """ + str(scores["wordPrefixTitle"]) + """
        const val WORD_PREFIX_EN_TITLE = """ + str(scores["wordPrefixEnTitle"]) + """
        const val EXACT_SYNONYM = """ + str(scores["exactSynonym"]) + """
        const val PREFIX_SYNONYM = """ + str(scores["prefixSynonym"]) + """
        const val CONTAINS_SYNONYM = """ + str(scores["containsSynonym"]) + """
        const val SUBSTRING_TITLE = """ + str(scores["substringTitle"]) + """
        const val CONTAINS_CATEGORY = """ + str(scores["containsCategory"]) + """
        const val SPEC_OR_NOTES = """ + str(scores["specOrNotes"]) + """
    }
}
"""
    with io.open(KT_OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(kt_code)
    print(f"{KT_OUT} generated")

    # 2. Sync prototype/index.html if needed
    if os.path.exists(PROTO):
        proto_html = io.open(PROTO, encoding="utf-8").read()
        # The WHOLE config, not one constant. Writing only STEM_COST left
        # eleven score tiers as hand-typed literals in the prototype, and one
        # of them - the passport tier - had already drifted out of existence
        # there while living in the JSON and in Kotlin. "Single source" means
        # the other copies cannot hold a number of their own.
        block = "const STEM_COST = %d;\nconst RANK = %s;" % (
            stem_cost,
            json.dumps(
                dict(minStemLength=data["minStemLength"],
                     maxDroppedChars=data["maxDroppedChars"], **scores),
                ensure_ascii=False, indent=2).replace("\n", "\n"),
        )
        pattern = re.compile(
            r"const STEM_COST = \d+;(?:\nconst RANK = \{(?:[^{}]|\{[^{}]*\})*\};)?")
        if not pattern.search(proto_html):
            print("could not find the ranking block in " + PROTO)
            return 1
        updated = pattern.sub(lambda _: block, proto_html, count=1)
        if updated != proto_html:
            io.open(PROTO, "w", encoding="utf-8", newline="\n").write(updated)
            print("%-58s ranking config injected" % PROTO)

    return 0

if __name__ == "__main__":
    sys.exit(main())
