package app.hullbeat.domain.search

/**
 * GENERATED by tools/make_search_config.py from design/search-ranking.json - do not edit.
 *
 * Scoring and morphological rules for HullBeat search (docs/search-spec.md).
 */
object SearchConfig {
    const val STEM_COST = 12
    const val MIN_STEM_LENGTH = 3
    const val MAX_DROPPED_CHARS = 2

    object Scores {
        const val EXACT_TITLE = 120
        const val EXACT_EN_TITLE = 110
        const val PREFIX_TITLE = 90
        const val PREFIX_EN_TITLE = 85
        const val WORD_PREFIX_TITLE = 70
        const val WORD_PREFIX_EN_TITLE = 65
        const val EXACT_SYNONYM = 55
        const val PREFIX_SYNONYM = 45
        const val CONTAINS_SYNONYM = 35
        const val SUBSTRING_TITLE = 40
        const val CONTAINS_CATEGORY = 30
        const val SPEC_OR_NOTES = 20
    }
}
